config/routes.rb
Sims::Application.routes.draw do

  resources :users, :divorces, :weddings

  resources :user_sessions
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :inhabitants do
    get :church, on: :collection
    get :court, on: :collection
  end

  match 'inhabitants/church' => 'inhabitants#church', :via => [:get], :as => :church
  match 'inhabitants/court' => 'inhabitants#court', :via => [:get], :as => :court

  match 'login' => 'user_sessions#new', :via => [:get, :post], :as => :login
  match 'logout' => 'user_sessions#destroy', :via => [:get, :post], :as => :logout

  root :to => 'user_sessions#new'
end

app/models/inhabitant.rb
class Inhabitant < ActiveRecord::Base
  attr_accessible :age, :first_name, :gender, :last_name
  validates_presence_of :first_name, :last_name, :gender
  validates :gender, :presence => true, :inclusion => {:in => %w(Male Female)}
  validates :age, :presence => true, :numericality => {:only_integer => true, :greater_than => 0}
  validates_uniqueness_of :first_name, :scope => :last_name, :message => 'and Last name already exists for an other inhabitant'
  # validate :is_unique
  validate :can_update_age, on: :update

  belongs_to :wedding
  belongs_to :user

  def to_s
    first_name+' '+last_name
  end

  private
  def can_update_age
    unless Wedding.find_by_id(self.id).nil?
       if age < 18
        errors.add(:age, 'Only adult can get married')
       end
    end
  end

  #TODO: finalize this validation
  def is_unique 
    user = User.find_by_id(session[:user_id])
    inhabitants = Inhabitant.where( "first_name = ? and last_name = ?", :first_name, :last_name)

    inhabitants.each
    if inhabitant and inhabitant.size > 1 
      errors.add(:first_name, 'and Lastname already exists for an other inhabitant')
    end
  end

end

app/controllers/inhabitants_controller.rb
class InhabitantsController < ApplicationController

  # GET /inhabitants
  # GET /inhabitants.json
  def index
    @inhabitants = Inhabitant.where(:user_id => session[:user_id])
    respond_to do |format|
      format.html # index.html.save.erb
      format.json { render json: @inhabitants }
    end
  end

  # GET /inhabitants/new
  # GET /inhabitants/new.json
  def new
    @inhabitant = Inhabitant.new
    @inhabitant.user = User.find(session[:user_id])
    @inhabitant.user_id = session[:user_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inhabitant }
    end
  end

  # GET /inhabitants/1/edit
  def edit
    @inhabitant = Inhabitant.find(params[:id])
  end

  # POST /inhabitants
  # POST /inhabitants.json
  def create
    @inhabitant = Inhabitant.new(params[:inhabitant])
    @inhabitant.user_id = session[:user_id]
    respond_to do |format|
      if @inhabitant.save
        format.html { redirect_to inhabitants_url, notice: 'Inhabitant was successfully created.' }
        format.json { render json: @inhabitant, status: :created, location: @inhabitant }
      else
        format.html { render action: "new" }
        format.json { render json: @inhabitant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inhabitants/1
  # PUT /inhabitants/1.json
  def update
    @inhabitant = Inhabitant.find_by_id(params[:id])

    respond_to do |format|
      if @inhabitant.update_attributes(params[:inhabitant])
        format.html { redirect_to inhabitants_url, notice: 'Inhabitant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inhabitant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inhabitants/1
  # DELETE /inhabitants/1.json
  def destroy
    @inhabitant = Inhabitant.find_by_id(params[:id])
    @inhabitant.destroy

    respond_to do |format|
      format.html { redirect_to inhabitants_url }
      format.json { head :no_content }
    end
  end

  # GET /inhabitants/church
  def church
    @inhabitants = Inhabitant.all

    respond_to do |format|
      format.html { render action: 'church'}
    end
  end

  # GET /inhabitants/court
  def court
    @inhabitants = Inhabitant.all

    respond_to do |format|
      format.html { render action: 'court'}
    end
  end
end

app/helpers/inhabitants_helper.rb
module InhabitantsHelper
end

app/views/inhabitants/_church_court.html.erb
<table class="table table-striped">
  <tr>
    <th></th>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Married with</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% Inhabitant.where(:user_id => session[:user_id]).each do |inhabitant| %>
      <tr>
        <td>
          <% if inhabitant.gender == 'Female' %>
              <img src="/img/female.png">
          <% else %>
              <img src="/img/male.png">
          <% end %>
        </td>
        <td><%= inhabitant.first_name %></td>
        <td><%= inhabitant.last_name %></td>
        <td><%= inhabitant.gender %></td>
        <td><%= inhabitant.age %></td>
        <% spouse= Wedding.get_spouse(inhabitant.id) %>
        <td>
          <% if spouse.nil? %>
              <%= "--" %>
          <% else %>
              <%= spouse.first_name %>  <%= spouse.last_name %>
          <% end %>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  <% end %>
</table>

app/views/inhabitants/_form.html.erb
<%= form_for(@inhabitant) do |f| %>
    <% if @inhabitant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@inhabitant.errors.count, "error") %> prohibited this inhabitant from being saved:</h2>

          <ul>
            <% @inhabitant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <section>
      <div class="form-group">
        <div class="field">
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.label :gender %>
          <%= f.select :gender, %w(Male Female) %>
        </div>

        <div class="field">
          <%= f.label :age %>
          <%= f.number_field :age %>
        </div>
      </div>
    </section>
    <br/>
    <section class="form-group">
      <div class="actions">
        <%= f.submit class: 'btn btn-info' %>
      </div>
    </section>
<% end %>

app/views/inhabitants/church.html.erb
<div class="alert alert-danger">
  <h1>Smart-Sims in Church</h1>
</div>
<hr>

<%= render 'church_court' %>

<hr>
<%= link_to 'Inhabitants list', inhabitants_path, class: 'btn btn-info' %>
<%= link_to 'Get married', new_wedding_path, class: 'btn btn-info' %>
<br/>

app/views/inhabitants/court.html.erb
<div class="alert alert-danger">
  <h1>Smart-Sims in Court</h1>
</div>
<hr>

<%= render 'church_court' %>

<hr>

<%= link_to 'Inhabitants list', inhabitants_path, class: 'btn btn-info' %>
<%= link_to 'Divorce', new_divorce_path, class: 'btn btn-info' %>
<br/>

app/views/inhabitants/edit.html.erb
<div class="alert alert-danger">
  <h1>Editing inhabitant</h1>
</div>
<hr>

<%= form_for(@inhabitant) do |f| %>
    <% if @inhabitant.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@inhabitant.errors.count, "error") %> prohibited this inhabitant from being saved:</h2>

          <ul>
            <% @inhabitant.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="field">
      <%= f.label :age %>
      <%= f.number_field :age %>
    </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-info' %>
    </div>
<% end %>

<hr>
<%= link_to 'Back', inhabitants_path, class: 'btn btn-info' %>

app/views/inhabitants/index.html.erb
<div class="alert alert-danger">
  <h1>Smart-Sims at Home</h1>
</div>
<hr>

<table class="table table-striped">
  <tr>
    <th></th>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Married with</th>
    <th>Edit</th>
    <th>Delete</th>
    <th></th>
  </tr>

  <% Inhabitant.where(:user_id => session[:user_id]).each do |inhabitant| %>
      <tr>
        <td>
          <% if inhabitant.gender == 'Female' %>
              <img src="/img/female.png">
          <% else %>
              <img src="/img/male.png">
          <% end %>
        </td>
        <td><%= inhabitant.first_name %></td>
        <td><%= inhabitant.last_name %></td>
        <td><%= inhabitant.gender %></td>
        <td><%= inhabitant.age %></td>
        <% spouse= Wedding.get_spouse(inhabitant.id) %>
        <td>
          <% if spouse.nil? %>
              <%= '--' %>
          <% else %>
              <%= spouse.first_name %>  <%= spouse.last_name %>
          <% end %>
        </td>
        <td><%= link_to image_tag('/img/edit2.png'), edit_inhabitant_path(inhabitant) %></td>
        <td><%= link_to image_tag('/img/delete3.png'), inhabitant, method: :delete, data: {confirm: 'Are you sure to delete the inhabitant: '+ inhabitant.to_s+' ?'} %></td>
        <td></td>
      </tr>
  <% end %>
</table>

<hr>

<%= link_to 'New Inhabitant', new_inhabitant_path, class: 'btn btn-info' %>
<%= link_to 'Go to church', church_path, class: 'btn btn-info' %>
<%= link_to 'Go to Court', court_path, class: 'btn btn-info' %>
<br/>

app/views/inhabitants/new.html.erb
<div class="alert alert-danger">
  <h1>New Smart-Sim</h1>
</div>
<hr>

<%= render 'form' %>

<hr>

<%= link_to 'Back', inhabitants_path, class: 'btn btn-info' %>

app/views/inhabitants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @inhabitant.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @inhabitant.last_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @inhabitant.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @inhabitant.age %>
</p>

<%= link_to 'Edit', edit_inhabitant_path(@inhabitant), class: 'btn btn-info' %>
<%= link_to 'Back', inhabitants_path, class: 'btn btn-info' %>