config/routes.rb
Sims::Application.routes.draw do

  resources :users, :divorces, :weddings

  resources :user_sessions
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :inhabitants do
    get :church, on: :collection
    get :court, on: :collection
  end

  match 'inhabitants/church' => 'inhabitants#church', :via => [:get], :as => :church
  match 'inhabitants/court' => 'inhabitants#court', :via => [:get], :as => :court

  match 'login' => 'user_sessions#new', :via => [:get, :post], :as => :login
  match 'logout' => 'user_sessions#destroy', :via => [:get, :post], :as => :logout

  root :to => 'user_sessions#new'
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  attr_accessible :first_spouse_id, :second_spouse_id

  has_many :inhabitants
  validate :all_wedding_errors
  validates_presence_of :first_spouse_id, :second_spouse_id

  def self.get_spouse(id)
    wedding = Wedding.find_by_first_spouse_id(id)
    unless wedding.nil?
      return Inhabitant.find_by_id(wedding.second_spouse_id)
    end
    wedding = Wedding.find_by_second_spouse_id(id)
    unless wedding.nil?
      return Inhabitant.find_by_id(wedding.first_spouse_id)
    end
  end

  def self.get_wedding_by_spouse_id(spouse_id)
    wedding = Wedding.find_by_first_spouse_id(spouse_id)
    unless wedding.nil?
      return wedding
    end
    wedding =  Wedding.find_by_second_spouse_id(spouse_id)
    unless wedding.nil?
      return wedding
    end
  end

  private
  def get_married_with_himself
    first_spouse_id == second_spouse_id
  end

  def all_wedding_errors
    if get_married_with_himself then
      errors.add(:second_spouse_id, 'wedding can only be done between two different persons')
    else
      not_adults_first_spouse_error()
      not_adults_second_spouse_error()
      gay_wedding_error()
      first_spouse_already_married()
      second_spouse_already_married()

    end
  end

  def not_adults_first_spouse_error
      if Inhabitant.find_by_id(first_spouse_id).age < 18 then
        errors.add(:first_spouse_id, 'Only adult can get married')
      end
  end

  def not_adults_second_spouse_error
      if Inhabitant.find_by_id(second_spouse_id).age < 18  then
        errors.add(:second_spouse_id, 'Only adult can get married')
      end
  end

  def gay_wedding_error
      if Inhabitant.find_by_id(first_spouse_id).gender == Inhabitant.find_by_id(second_spouse_id).gender then
        errors.add(:second_spouse_id, 'Gay wedding not yet permit')
      end
  end

  def first_spouse_already_married
      unless Wedding.find_by_first_spouse_id(first_spouse_id).nil? and Wedding.find_by_second_spouse_id(first_spouse_id).nil? then
            errors.add(:first_spouse_id, 'already married')
      end
  end

  def second_spouse_already_married
      unless Wedding.find_by_second_spouse_id(second_spouse_id).nil? and Wedding.find_by_first_spouse_id(second_spouse_id).nil? then
        errors.add(:second_spouse_id, 'already married')
      end
  end

end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController

  # GET /weddings/new
  # GET /weddings/new.json
  def new
    @wedding = Wedding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wedding }
    end
  end

  # POST /weddings
  # POST /weddings.json
  def create
    @wedding = Wedding.new(params[:wedding])

    respond_to do |format|
      if @wedding.save
        format.html { redirect_to inhabitants_path }
        format.json { render inhabitants_path }
      else
        format.html { render action: "new" }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weddings/1
  # DELETE /weddings/1.json
  def destroy
    @wedding = Wedding.find(params[:id])
    @wedding.destroy

    respond_to do |format|
      format.html { redirect_to weddings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/_form.html.erb
<%= form_for(@wedding) do |f| %>
    <% if @wedding.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@wedding.errors.count, "error") %> prohibited this wedding from being saved:</h2>

          <ul>
            <% @wedding.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% map_name_id = Inhabitant.where(:user_id => session[:user_id]).map { |inhabitant| [inhabitant.first_name.to_s.concat(' '+inhabitant.last_name), inhabitant.id] } %>
    <div class="field">
      <%= f.label :first_person %>
      <%= f.select :first_spouse_id, map_name_id %>
    </div>
    <div class="field">
      <%= f.label :second_person %>
      <%= f.select :second_spouse_id, map_name_id %>
    </div>
    <br/>
    <div class="actions">
      <%= f.submit 'Get Married', class: 'btn btn-info' %>
    </div>
<% end %>

app/views/weddings/new.html.erb
<div class="alert alert-danger">
  <h1>Inhabitants in Church</h1>
</div>
<hr>

<table class="table table-striped">
  <tr>
    <th></th>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Married with</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% Inhabitant.where(:user_id => session[:user_id]).each do |inhabitant| %>
      <tr>
        <td>
          <% if (inhabitant.gender == 'Female') %>
              <img src="/img/female.png">
          <% else %>
              <img src="/img/male.png">
          <% end %>
        </td>
        <td><%= inhabitant.first_name %></td>
        <td><%= inhabitant.last_name %></td>
        <td><%= inhabitant.gender %></td>
        <td><%= inhabitant.age %></td>
        <% spouse= Wedding.get_spouse(inhabitant.id) %>
        <td>
          <% if spouse.nil? %>
              <%= "--" %>
          <% else %>
              <%= spouse.first_name %>  <%= spouse.last_name %>
          <% end %>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  <% end %>
</table>

<hr>

<div class="btn btn-info"> <%= link_to 'Inhabitants list', inhabitants_path %></div>
<div class="btn btn-info" data-toggle="modal" href="#weddingModal"><%= link_to 'Get married', new_wedding_path %> </div>
<br/>

<div class="modal" id="weddingModal">
  <div class="modal-header">
    <div class="alert alert-danger">
      <h3>New marriage</h3>
    </div>
  </div>
  <div class="modal-body">
    <%= render 'form' %>
  </div>

  <div class="modal-footer">
    <%= link_to 'Back', church_url, class: 'btn btn-info' %>
  </div>
</div>