config/routes.rb
Sims::Application.routes.draw do

  resources :users, :divorces, :weddings

  resources :user_sessions
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :inhabitants do
    get :church, on: :collection
    get :court, on: :collection
  end

  match 'inhabitants/church' => 'inhabitants#church', :via => [:get], :as => :church
  match 'inhabitants/court' => 'inhabitants#court', :via => [:get], :as => :court

  match 'login' => 'user_sessions#new', :via => [:get, :post], :as => :login
  match 'logout' => 'user_sessions#destroy', :via => [:get, :post], :as => :logout

  root :to => 'user_sessions#new'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

    def new
      # @user = User.new
    end

    def create
      respond_to do |format|
        user = login params[:username], params[:password]
        unless user then
          temp_user =  User.find_by_email(params[:username])
          if temp_user
            user = login temp_user.username, params[:password]
          end
        end
        if user
          session[:user_id] = user.id
          format.html { redirect_back_or_to(inhabitants_path, :notice => 'Login successful.') }
          format.xml { render :xml => @user, :status => :created, :location => @user }
        else
          format.html { redirect_to(:login, :notice => 'Logged out!') }
          format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    end

    def destroy
      session[:user_id] = nil
      logout
      redirect_to(:login, :notice => 'Logged out!')
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <div class=" form-group">
      <div class="form-control form-bloc">
        <%= label_tag 'Email' %>
        <%= text_field_tag :username %>
      </div>
    </div>

    <div class="form-control form-bloc">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <br/>
    <div class="actions form-bloc">
      <%= submit_tag "Sign in", class: 'btn btn-info' %>
    </div>
<% end %> 

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="alert alert-danger">
  <h1>Sign in</h1>
</div>
<hr>
<%= render 'form' %>
You have no account ? <%= link_to 'Sign up', new_user_path, class: 'btn btn-link' %>
<hr>